name: copilot_poc
description: "Prova de conceito experimental do uso de Copilot pra construção de testes unitários em um projeto Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  dartz: ^0.10.1
  device_preview: ^1.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_native_splash: ^2.3.11
  font_awesome_flutter: ^10.7.0
  go_router: ^16.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.0.2+1
  nested: ^1.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
